services:
  - type: web
    name: api-learning-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./backend/database/api_learning.db
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    disk:
      name: api-learning-disk
      mountPath: /opt/render/project/src/backend/database
      sizeGB: 1